### ISSUE TITLE
Bug: CraftGuide crashes

### ISSUE THREAD

**Issue by Sranshaft** [grompe/BTWTweak#10]
BTWTweaks Version 1.0 and BTW Version 4-AABBBbbbbbb

`java.lang.NoSuchFieldError: fcKiln
	at GPEInteropCraftGuide.invoke(GPEInteropCraftGuide.java:448)
	at com.sun.proxy.$Proxy0.filterRecipes(Unknown Source)
	at uristqwerty.CraftGuide.RecipeCache.filterRawRecipes(RecipeCache.java:246)
	at uristqwerty.CraftGuide.RecipeCache.reset(RecipeCache.java:49)
	at uristqwerty.CraftGuide.RecipeCache.<init>(RecipeCache.java:39)
	at uristqwerty.CraftGuide.GuiCraftGuide.<init>(GuiCraftGuide.java:40)
	at uristqwerty.CraftGuide.GuiCraftGuide.getInstance(GuiCraftGuide.java:63)
	at uristqwerty.CraftGuide.client.vanilla.CraftGuideClient_Vanilla.openGUI(CraftGuideClient_Vanilla.java:32)
	at CraftGuide_Vanilla.checkKeybind(CraftGuide_Vanilla.java:118)
	at ayc.a(GuiAchievement.java:98)
	at net.minecraft.client.Minecraft.K(Minecraft.java:899)
	at net.minecraft.client.Minecraft.run(Minecraft.java:761)
	at java.lang.Thread.run(Unknown Source)`

**Comment by grompe** [comment]
Please redownload BTWTweak v1.0.
