### ISSUE TITLE
Bug: Error with new Deco Addon

### ISSUE THREAD

**Issue by Sranshaft** [grompe/BTWTweak#9]
2017-04-04 18:54:50 [SERVER] [INFO] Error while integrating with Deco Add-On!
java.lang.NullPointerException
	at GPEBTWTweak.postPostInitialize(GPEBTWTweak.java:512)
	at GPEBTWTweak.OnLanguageLoaded(GPEBTWTweak.java:790)
	at FCAddOnHandler.OnLanguageLoaded(FCAddOnHandler.java:135)
	at bp.a(StringTranslate.java:159)
	at bp.<init>(StringTranslate.java:31)
	at jc.<init>(EntityPlayerMP.java:16)
	at gu.a(ServerConfigurationManager.java:340)
	at bjj.b(SourceFile:67)
	at net.minecraft.server.MinecraftServer.r(SourceFile:480)
	at net.minecraft.server.MinecraftServer.q(SourceFile:397)
	at bjg.q(IntegratedServer.java:126)
	at net.minecraft.server.MinecraftServer.run(SourceFile:331)
	at gp.run(SourceFile:573)

**Comment by Sranshaft** [comment]
Disregard, PEBKAC.

**Comment by grompe** [comment]
Stuff happens. How did you manage?
